export const questions = [
    "1. Tengo buen carácter.",
    "2. Siempre trato de mantener distancia en relación a las personas.",
    "3. Si alguien me insulta o me ofende intento mantener la calma.",
    "4. He tenido éxito en varias cosas.",
    "5. No presto demasiada atención, o no me importa demasiado, el efecto que mis acciones puedan tener en otras personas.",
    "6. Me cuesta enfocarme en una tarea por demasiado tiempo.",
    "7. Soy una persona prudente.",
    "8. La mayoría de las veces puedo controlar mis reacciones emocionales (por ejemplo: enojo, tristeza, alegría, miedo) si estoy en un lugar en el que no sería apropiado hacer un escándalo.",
    "9. Si alguien me contradice, empiezo a dudar de mí mismo.",
    "10. Generalmente puedo mantenerme concentrado durante un tiempo considerable.",
    "11. Establezco estándares personales que me son muy difíciles de cumplir.",
    "12. Usualmente estoy tranquilo/a incluso cuando hay cosas que están fuera de mi control.",
    "13. Puedo sentirme cómodo/a al mostrarme sensible frente a los demás.",
    "14. Me asusto cuando siento que un vínculo se vuelve demasiado cercano.",
    "15. Suelo ser muy distraído/a.",
    "16. Sé como lograr que otros se encarguen de mis obligaciones si no me dan ganas de hacer algo.",
    "17. Me cuesta mucho estar solo/a.",
    "18. Pocas cosas me dan placer en la vida.",
    "19. No entiendo en absoluto cuáles son las intenciones de las personas.",
    "20. A veces me dan ganas de romper todo.",
    "21. Prefiero quedarme en casa aunque tenga la opción de salir con amigos.",
    "22. A veces no sé si estoy despierto/a o soñando.",
    "23. Prefiero no involucrarme en actividades que implican un alto riesgo.",
    "24. Es fácil aprovecharse de la gente.",
    "25. No puedo tolerar cuando las diferencias de opinión son muy marcadas.",
    "26. Usualmente logro concentrarme en mis tareas aunque me interrumpan.",
    "27. A veces pierdo el control y consumo demasiadas drogas.",
    "28. Generalmente no cumplo con mis compromisos.",
    "29. Generalmente me gusta estar solo/a.",
    "30. Me preocupo más que el resto de las personas.",
    "31. Me emborracho casi todas las semanas.",
    "32. No suelo tener muchas interacciones positivas o agradables con las personas.",
    "33. Las mentiras son necesarias.",
    "34. Alguien observa todo lo que hago.",
    "35. Prefiero no correr grandes riesgos.",
    "36. Me cuesta cumplir con mis responsabilidades.",
    "37. No soy ni más ni menos importante que los demás.",
    "38. Me interesa muy poco establecer vínculos cercanos.",
    "39. Soy de evitar riesgos innecesarios.",
    "40. A menudo me involucro en causas solidarias.",
    "41. Si tengo un objetivo claro me enfoco en hacer aquello necesario para alcanzarlo.",
    "42. La gente puede confiar en mí.",
    "43. Tengo dificultades para fijar metas personales.",
    "44. Normalmente es difícil hacerme perder la calma.",
    "45. Habitualmente puedo conseguir lo que quiero manejándome honestamente.",
    "46. Puedo percibir la presencia de seres que no están físicamente aquí.",
    "47. Tengo fallas como cualquier ser humano.",
    "48. Soy de ayudar a quienes están sufriendo.",
    "49. Suelo sentir que lo que hago tiene importancia.",
    "50. Me cuesta entender cómo me siento o lo que hago.",
    "51. En ocasiones veo cosas que no están realmente allí.",
    "52. Soy de emocionarme fácilmente.",
    "53. Generalmente si algo me irrita intento solucionarlo de buena manera.",
    "54. Sé cómo hacer que la gente haga lo que quiero.",
    "55. Para estar en ventaja a veces hay que cambiar un poco cómo se cuentan los hechos.",
    "56. Si puedo evitarlo, prefiero no ir a eventos sociales.",
    "57. A veces veo cosas, personas o animales que los demás no ven.",
    "58. Me siento incómodo/a en reuniones sociales.",
    "59. Siempre intento entablar un trato amable con las personas aunque no me caigan bien.",
    "60. Me sentiría incómodo/a si tuviera que mentir.",
    "61. Usualmente me hago cargo de mis responsabilidades.",
    "62. Generalmente me siento tenso/a.",
    "63. Antes de hacer algo pienso qué consecuencias podrían tener mis actos.",
    "64. Si tengo diferencias con alguien, prefiero hablar calmado/a.",
    "65. Siempre espero que me traten de igual manera que a los demás, no espero un trato preferencial.",
    "66. Antes de tomar algún riesgo pienso en las posibles consecuencias.",
    "67. En ocasiones abandono mi cuerpo y me veo desde afuera.",
    "68. Aunque se requiera cierta urgencia, siempre trato de pensar lo que voy a hacer.",
    "69. Soy una persona valiosa.",
    "70. Mayormente me siento a gusto con mi vida.",
    "71. Normalmente soy bastante amable con todas las personas, incluyendo gente que me cae mal.",
    "72. Si sorpresivamente tengo una emoción intensa, casi siempre puedo manejar mi forma de actuar y pensar.",
    "73. Cuando halago a alguien es porque realmente lo pienso.",
    "74. A veces me siento tan mal que no lo puedo tolerar.",
    "75. Soy sincero/a en cuanto a mis intenciones cuando pido ayuda.",
    "76. Casi nadie está a mi nivel.",
    "77. Ciertas imágenes o situaciones pueden ponerme sensible.",
    "78. Casi nada me entusiasma.",
    "79. Soy una persona paciente con los demás.",
    "80. Casi siempre prefiero no tomar riesgos innecesarios.",
    "81. Los logros de los demás son igual de importantes que los míos.",
    "82. Casi siempre puedo concentrarme en la mayoría de las cosas que hago.",
    "83. Si hice una promesa, hago todo lo que está en mis manos para cumplirla.",
    "84. Soy una persona tranquila.",
    "85. La gente suele ser tonta.",
    "86. La mayor parte del tiempo estoy satisfecho/a conmigo mismo.",
    "87. Cuando me propongo algo pongo toda mi atención en lograrlo.",
    "88. Cuando las personas están descontentas conmigo, me es difícil mantener mis emociones bajo control.",
    "89. Siempre pienso en la posibilidad de que las cosas salgan mal.",
    "90. La mayor parte del tiempo la vida me parece hermosa.",
    "91. Generalmente ayudo a los demás.",
    "92. Me altero fácilmente.",
    "93. No puedo dejar de estar en alerta.",
    "94. Suelo mostrar mis emociones.",
    "95. Me suelo enojar mucho más que otras personas.",
    "96. En tiempos difíciles a veces pierdo de vista lo que es importante para mí.",
    "97. Soy una persona segura de sí misma.",
    "98. Haga lo que haga siempre siento culpa.",
    "99. Intento conseguir lo que quiero mostrándome tal cual soy.",
    "100. Suelo rechazar a las personas.",
    "101. Habitualmente siento que tengo energía para hacer cosas.",
    "102. Generalmente soy una persona calmada.",
    "103. Me resulta difícil lograr mis objetivos porque me distraigo.",
    "104. Siento que un ser superior me asignó una misión especial.",
    "105. Necesito confirmar constantemente que las personas me quieren.",
    "106. Generalmente disfruto de la vida.",
    "107. A veces tomo demasiado alcohol.",
    "108. Tengo poderes especiales.",
    "109. Casi siempre me resulta fácil concentrarme en lo que hay que hacer.",
    "110. A diferencia de la mayoría de las personas, yo hago todo bien.",
    "111. Muchas veces me enojo de repente y no lo puedo controlar.",
    "112. Tengo una gran necesidad de que los otros aprueben como soy.",
    "113. Para conseguir lo que se quiere a veces es necesario no contar toda la verdad.",
    "114. Me agrada la mayoría de mis actividades cotidianas.",
    "115. Me siento culpable si mis acciones lastimaron a alguien.",
    "116. Soy una persona sensible a lo que ocurre a mi alrededor.",
    "117. A veces no soy muy cooperativo/a porque los demás no cumplen con mis estándares.",
    "118. No suelo disfrutar de la vida.",
    "119. Soy una persona que planifica antes de actuar.",
    "120. La mayor parte del tiempo me siento bien."
];
